# Network speed
set -g @net_speed_interfaces "wlo1"

set-option -g @tmux-autoreload-configs '/home/nihal/dotfiles/.config/tmux/statusline.conf,/home/nihal/dotfiles/.config/tmux/tpm-plugins.conf,/home/nihal/dotfiles/.config/tmux/utility.conf'
